[2025-05-09T12:33:03.511+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: graph_analysis.run_jupyter manual__2025-05-09T12:30:21.406997+00:00 [queued]>
[2025-05-09T12:33:03.517+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: graph_analysis.run_jupyter manual__2025-05-09T12:30:21.406997+00:00 [queued]>
[2025-05-09T12:33:03.517+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-05-09T12:33:03.527+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_jupyter> on 2025-05-09 12:30:21.406997+00:00
[2025-05-09T12:33:03.531+0000] {standard_task_runner.py:57} INFO - Started process 15248 to run task
[2025-05-09T12:33:03.533+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'graph_analysis', 'run_jupyter', 'manual__2025-05-09T12:30:21.406997+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/graph_analysis.py', '--cfg-path', '/tmp/tmptcwdyp59']
[2025-05-09T12:33:03.533+0000] {standard_task_runner.py:85} INFO - Job 397: Subtask run_jupyter
[2025-05-09T12:33:03.547+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-09T12:33:03.577+0000] {task_command.py:410} INFO - Running <TaskInstance: graph_analysis.run_jupyter manual__2025-05-09T12:30:21.406997+00:00 [running]> on host d3632ec65b22
[2025-05-09T12:33:03.646+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='graph_analysis' AIRFLOW_CTX_TASK_ID='run_jupyter' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T12:30:21.406997+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T12:30:21.406997+00:00'
[2025-05-09T12:33:03.648+0000] {python.py:183} INFO - Done. Returned value was: 32512
[2025-05-09T12:33:03.669+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=graph_analysis, task_id=run_jupyter, execution_date=20250509T123021, start_date=20250509T123303, end_date=20250509T123303
[2025-05-09T12:33:03.705+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-09T12:33:03.731+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
