[2025-05-06T13:00:58.702+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: graph_analysis.create_mart manual__2025-05-06T12:58:14.315561+00:00 [queued]>
[2025-05-06T13:00:58.708+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: graph_analysis.create_mart manual__2025-05-06T12:58:14.315561+00:00 [queued]>
[2025-05-06T13:00:58.708+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-05-06T13:00:58.716+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_mart> on 2025-05-06 12:58:14.315561+00:00
[2025-05-06T13:00:58.720+0000] {standard_task_runner.py:57} INFO - Started process 1974 to run task
[2025-05-06T13:00:58.722+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'graph_analysis', 'create_mart', 'manual__2025-05-06T12:58:14.315561+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/graph_analysis.py', '--cfg-path', '/tmp/tmpq2fww_nh']
[2025-05-06T13:00:58.722+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask create_mart
[2025-05-06T13:00:58.733+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-06T13:00:58.758+0000] {task_command.py:410} INFO - Running <TaskInstance: graph_analysis.create_mart manual__2025-05-06T12:58:14.315561+00:00 [running]> on host 016737cbcc7e
[2025-05-06T13:00:58.813+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='graph_analysis' AIRFLOW_CTX_TASK_ID='create_mart' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T12:58:14.315561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T12:58:14.315561+00:00'
[2025-05-06T13:00:58.813+0000] {sql.py:265} INFO - Executing: 
    -- Обновляем витрину данных с графовой аналитикой
    INSERT INTO mart.fact_graph_analytics (
        transaction_id, client_id, datetime, amount, currency, 
        merchant, transaction_type, ip_network, category,
        community_id, influence_score, community_size
    )
    SELECT 
        t.transaction_id, 
        t.client_id, 
        t.datetime, 
        t.amount, 
        t.currency, 
        t.merchant, 
        t.transaction_type, 
        t.ip_network, 
        t.category,
        c.community_id, 
        c.influence_score, 
        c.community_size
    FROM 
        raw.masked_transactions t
    LEFT JOIN 
        graph.client_communities c ON t.client_id = c.client_id
    ON CONFLICT (transaction_id) 
    DO UPDATE SET
        community_id = EXCLUDED.community_id,
        influence_score = EXCLUDED.influence_score,
        community_size = EXCLUDED.community_size,
        created_at = NOW();
    
[2025-05-06T13:00:58.814+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-06T13:00:58.814+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-06T13:00:58.876+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-06T13:00:58.880+0000] {sql.py:374} INFO - Running statement: 
    -- Обновляем витрину данных с графовой аналитикой
    INSERT INTO mart.fact_graph_analytics (
        transaction_id, client_id, datetime, amount, currency, 
        merchant, transaction_type, ip_network, category,
        community_id, influence_score, community_size
    )
    SELECT 
        t.transaction_id, 
        t.client_id, 
        t.datetime, 
        t.amount, 
        t.currency, 
        t.merchant, 
        t.transaction_type, 
        t.ip_network, 
        t.category,
        c.community_id, 
        c.influence_score, 
        c.community_size
    FROM 
        raw.masked_transactions t
    LEFT JOIN 
        graph.client_communities c ON t.client_id = c.client_id
    ON CONFLICT (transaction_id) 
    DO UPDATE SET
        community_id = EXCLUDED.community_id,
        influence_score = EXCLUDED.influence_score,
        community_size = EXCLUDED.community_size,
        created_at = NOW();
    , parameters: None
[2025-05-06T13:00:58.885+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 348, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 379, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2025-05-06T13:00:58.893+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=graph_analysis, task_id=create_mart, execution_date=20250506T125814, start_date=20250506T130058, end_date=20250506T130058
[2025-05-06T13:00:58.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 197 for task create_mart (integer out of range
; 1974)
[2025-05-06T13:00:58.933+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-05-06T13:00:58.950+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
