[2025-04-30T17:12:14.883+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_superset_chart manual__2025-04-30T17:12:10.002037+00:00 [queued]>
[2025-04-30T17:12:14.889+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_superset_chart manual__2025-04-30T17:12:10.002037+00:00 [queued]>
[2025-04-30T17:12:14.889+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-30T17:12:14.899+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_superset_chart> on 2025-04-30 17:12:10.002037+00:00
[2025-04-30T17:12:14.902+0000] {standard_task_runner.py:57} INFO - Started process 595 to run task
[2025-04-30T17:12:14.904+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_superset_chart', 'manual__2025-04-30T17:12:10.002037+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmpupftpugf']
[2025-04-30T17:12:14.905+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask create_superset_chart
[2025-04-30T17:12:14.916+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T17:12:14.942+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_superset_chart manual__2025-04-30T17:12:10.002037+00:00 [running]> on host a2dde070184b
[2025-04-30T17:12:15.071+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_superset_chart' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T17:12:10.002037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T17:12:10.002037+00:00'
[2025-04-30T17:12:15.498+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/superset_sync.py", line 91, in t_chart
    data=payload,timeout=10).raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://superset:8088/api/v1/chart/
[2025-04-30T17:12:15.515+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=superset_sync, task_id=create_superset_chart, execution_date=20250430T171210, start_date=20250430T171214, end_date=20250430T171215
[2025-04-30T17:12:15.530+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 11 for task create_superset_chart (400 Client Error: BAD REQUEST for url: http://superset:8088/api/v1/chart/; 595)
[2025-04-30T17:12:15.558+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-30T17:12:15.593+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
