[2025-05-07T02:46:55.818+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: graph_analysis.create_mart manual__2025-05-07T02:44:07.882561+00:00 [queued]>
[2025-05-07T02:46:55.824+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: graph_analysis.create_mart manual__2025-05-07T02:44:07.882561+00:00 [queued]>
[2025-05-07T02:46:55.824+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-05-07T02:46:55.834+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_mart> on 2025-05-07 02:44:07.882561+00:00
[2025-05-07T02:46:55.838+0000] {standard_task_runner.py:57} INFO - Started process 6730 to run task
[2025-05-07T02:46:55.841+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'graph_analysis', 'create_mart', 'manual__2025-05-07T02:44:07.882561+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/graph_analysis.py', '--cfg-path', '/tmp/tmp49_acytw']
[2025-05-07T02:46:55.841+0000] {standard_task_runner.py:85} INFO - Job 254: Subtask create_mart
[2025-05-07T02:46:55.854+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T02:46:55.882+0000] {task_command.py:410} INFO - Running <TaskInstance: graph_analysis.create_mart manual__2025-05-07T02:44:07.882561+00:00 [running]> on host 5c5d1775d94e
[2025-05-07T02:46:55.947+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='graph_analysis' AIRFLOW_CTX_TASK_ID='create_mart' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T02:44:07.882561+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T02:44:07.882561+00:00'
[2025-05-07T02:46:55.947+0000] {sql.py:265} INFO - Executing: 
    INSERT INTO mart.fact_graph_analytics (
        transaction_id, client_id, datetime, amount, currency, 
        merchant, transaction_type, ip_network, category,
        community_id, influence_score, community_size, w_degree
    )
    SELECT 
        t.transaction_id, 
        t.client_id, 
        t.datetime, 
        t.amount, 
        t.currency, 
        t.merchant, 
        t.transaction_type, 
        t.ip_network, 
        t.category,
        c.community_id, 
        c.influence_score, 
        c.community_size,
        c.w_degree
    FROM 
        raw.masked_transactions t
    LEFT JOIN 
        graph.client_communities c ON t.client_id = c.client_id
    ON CONFLICT (transaction_id) 
    DO UPDATE SET
        community_id = EXCLUDED.community_id,
        influence_score = EXCLUDED.influence_score,
        community_size = EXCLUDED.community_size,
        w_degree = EXCLUDED.w_degree,
        created_at = NOW();
    
[2025-05-07T02:46:55.948+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-07T02:46:55.948+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-07T02:46:55.985+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-07T02:46:55.989+0000] {sql.py:374} INFO - Running statement: 
    INSERT INTO mart.fact_graph_analytics (
        transaction_id, client_id, datetime, amount, currency, 
        merchant, transaction_type, ip_network, category,
        community_id, influence_score, community_size, w_degree
    )
    SELECT 
        t.transaction_id, 
        t.client_id, 
        t.datetime, 
        t.amount, 
        t.currency, 
        t.merchant, 
        t.transaction_type, 
        t.ip_network, 
        t.category,
        c.community_id, 
        c.influence_score, 
        c.community_size,
        c.w_degree
    FROM 
        raw.masked_transactions t
    LEFT JOIN 
        graph.client_communities c ON t.client_id = c.client_id
    ON CONFLICT (transaction_id) 
    DO UPDATE SET
        community_id = EXCLUDED.community_id,
        influence_score = EXCLUDED.influence_score,
        community_size = EXCLUDED.community_size,
        w_degree = EXCLUDED.w_degree,
        created_at = NOW();
    , parameters: None
[2025-05-07T02:46:55.990+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 348, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 379, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "w_degree" of relation "fact_graph_analytics" does not exist
LINE 5: ...     community_id, influence_score, community_size, w_degree
                                                               ^

[2025-05-07T02:46:55.999+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=graph_analysis, task_id=create_mart, execution_date=20250507T024407, start_date=20250507T024655, end_date=20250507T024655
[2025-05-07T02:46:56.006+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 254 for task create_mart (column "w_degree" of relation "fact_graph_analytics" does not exist
LINE 5: ...     community_id, influence_score, community_size, w_degree
                                                               ^
; 6730)
[2025-05-07T02:46:56.053+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-05-07T02:46:56.087+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
