[2025-04-30T13:40:18.084+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_load.load_rates manual__2025-04-30T13:40:09.458908+00:00 [queued]>
[2025-04-30T13:40:18.090+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_load.load_rates manual__2025-04-30T13:40:09.458908+00:00 [queued]>
[2025-04-30T13:40:18.091+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-30T13:40:18.102+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_rates> on 2025-04-30 13:40:09.458908+00:00
[2025-04-30T13:40:18.108+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2025-04-30T13:40:18.110+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_load', 'load_rates', 'manual__2025-04-30T13:40:09.458908+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp8kre25bx']
[2025-04-30T13:40:18.111+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask load_rates
[2025-04-30T13:40:18.123+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T13:40:18.149+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_load.load_rates manual__2025-04-30T13:40:09.458908+00:00 [running]> on host ea0800df7ab4
[2025-04-30T13:40:18.223+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='extract_load' AIRFLOW_CTX_TASK_ID='load_rates' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T13:40:09.458908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T13:40:09.458908+00:00'
[2025-04-30T13:40:18.233+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-30T13:40:18.237+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_load.py", line 60, in gen_rates
    hook.run(f"DELETE FROM staging.currency_rates WHERE date='{ds}'")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-04-30T13:40:18.246+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_load, task_id=load_rates, execution_date=20250430T134009, start_date=20250430T134018, end_date=20250430T134018
[2025-04-30T13:40:18.254+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 45 for task load_rates (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 107)
[2025-04-30T13:40:18.282+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-30T13:40:18.303+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
