[2025-04-30T20:11:51.405+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T20:11:49.379313+00:00 [queued]>
[2025-04-30T20:11:51.411+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T20:11:49.379313+00:00 [queued]>
[2025-04-30T20:11:51.411+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-30T20:11:51.421+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_superset_dataset> on 2025-04-30 20:11:49.379313+00:00
[2025-04-30T20:11:51.424+0000] {standard_task_runner.py:57} INFO - Started process 7826 to run task
[2025-04-30T20:11:51.426+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_superset_dataset', 'manual__2025-04-30T20:11:49.379313+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmp89p6gx8e']
[2025-04-30T20:11:51.427+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask create_superset_dataset
[2025-04-30T20:11:51.438+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T20:11:51.463+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T20:11:49.379313+00:00 [running]> on host a2dde070184b
[2025-04-30T20:11:51.602+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_superset_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T20:11:49.379313+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T20:11:49.379313+00:00'
[2025-04-30T20:11:51.911+0000] {superset_sync.py:122} INFO - Dataset уже есть (id=1)
[2025-04-30T20:11:52.031+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/superset_sync.py", line 131, in t_dataset
    return ensure_dataset(sess, head, db_id(sess, head))
  File "/opt/airflow/dags/superset_sync.py", line 125, in ensure_dataset
    ensure_metric(sess, head, ds)      # ← новая строка
  File "/opt/airflow/dags/superset_sync.py", line 107, in ensure_metric
    sess.patch(url, headers=head, data=payload, timeout=10).raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: METHOD NOT ALLOWED for url: http://superset:8088/api/v1/dataset/1
[2025-04-30T20:11:52.039+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=superset_sync, task_id=create_superset_dataset, execution_date=20250430T201149, start_date=20250430T201151, end_date=20250430T201152
[2025-04-30T20:11:52.047+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 60 for task create_superset_dataset (405 Client Error: METHOD NOT ALLOWED for url: http://superset:8088/api/v1/dataset/1; 7826)
[2025-04-30T20:11:52.079+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-30T20:11:52.101+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
