[2025-05-07T21:43:45.963+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: graph_analysis.run_jupyter manual__2025-05-07T21:29:46.443501+00:00 [queued]>
[2025-05-07T21:43:45.968+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: graph_analysis.run_jupyter manual__2025-05-07T21:29:46.443501+00:00 [queued]>
[2025-05-07T21:43:45.968+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-05-07T21:43:45.976+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_jupyter> on 2025-05-07 21:29:46.443501+00:00
[2025-05-07T21:43:45.980+0000] {standard_task_runner.py:57} INFO - Started process 11253 to run task
[2025-05-07T21:43:45.982+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'graph_analysis', 'run_jupyter', 'manual__2025-05-07T21:29:46.443501+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/graph_analysis.py', '--cfg-path', '/tmp/tmpzq8sam4f']
[2025-05-07T21:43:45.982+0000] {standard_task_runner.py:85} INFO - Job 285: Subtask run_jupyter
[2025-05-07T21:43:45.993+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-07T21:43:46.017+0000] {task_command.py:410} INFO - Running <TaskInstance: graph_analysis.run_jupyter manual__2025-05-07T21:29:46.443501+00:00 [running]> on host 3530b0b864fd
[2025-05-07T21:43:46.124+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='graph_analysis' AIRFLOW_CTX_TASK_ID='run_jupyter' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T21:29:46.443501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-07T21:29:46.443501+00:00'
[2025-05-07T21:43:46.126+0000] {python.py:183} INFO - Done. Returned value was: 32512
[2025-05-07T21:43:46.144+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=graph_analysis, task_id=run_jupyter, execution_date=20250507T212946, start_date=20250507T214345, end_date=20250507T214346
[2025-05-07T21:43:46.194+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-07T21:43:46.224+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
